host = 'localhost'  # 数据库主机
user = 'root'  # 数据库用户名
passwd = 'Lcg19980319!'  # 数据库密码
port = 3306  # 数据库端口
db = 'netflavwuma'  # 数据库名称
dir = './content'  # 文件储存位置 默认是 redme文件同级的content
table = 'wuma'  # 数据库内表名称
field = 'netflav_id'  # 默认为id
start_page = 2  # 起始页
end_page = 5  # 结束页
start_url = 'https://netflav.com/uncensored'
